### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by s-light** [trinamic/TMCL-IDE-Nightly#1]
do you plan on add back linux nighlies?

quote from [your download site](https://www.trinamic.com/support/software/tmcl-ide/):
> TMCL-IDE nightly build and Linux version
> Visit our GitHub for nighly snapshots or latest Linux version of the TMCL-IDE.
---
i have looked into the history of the repository - and found
- https://github.com/trinamic/TMCL-IDE-Nightly/commit/284b12efeec88ed0601d07be4fb4004501f48120  `TMCL-IDE-3.0.19.0008.tar.gz` added
- https://github.com/trinamic/TMCL-IDE-Nightly/commit/30be5523f6bae6abba31368ee2ad3e398dbc5eb1 `TMCL-IDE-3.0.19.0008.tar.gz` changed
- https://github.com/trinamic/TMCL-IDE-Nightly/commit/e29a860a4aff5cae01263b3541e09e9724c6d31f `HowToStartLinuxTMCL-IDE.pdf` added
- https://github.com/trinamic/TMCL-IDE-Nightly/commit/917fea8e04bef20acb80d0e2f3561bf416d94bb1 ` TMCL-IDE-3.0.19.0008.tar.gz` deleted.

so in the past there was a nightly... ;-)

would be really cool if you can use this repro for the actual software development and not only the (nightly)releases..

**Comment by hadack** [comment]
Yes, that would be great.
Is even the latest version 3.0.22 on Linux available for download somewhere?

**Comment by trinamic-mj** [comment]
Now, we are looking for an automatic method to deliver the binaries, includes all libraries needed. This version will be placed on our website first. After that automatically nightly builds could be possible.
This will comming soon
