### ISSUE TITLE
Low: Remember CAN id search box range

### ISSUE THREAD

**Issue by dzid26** [trinamic/TMCL-IDE-Nightly#12]
**Suggestion**
Please add remembering Search ids after program restart similar to how bitrate is remembered:
![image](https://user-images.githubusercontent.com/841061/71709755-fc6d0880-2dc6-11ea-9842-5654f7adfdc2.png)

**Comment by dzid26** [comment]
Also, Reply ID doesn't seem to make a difference. It works, no matter the value.
So I am not sure what it does, but maybe it should be remembered too.

**Comment by trinamic-mj** [comment]
See next version
