### ISSUE TITLE
Misspecified module parameters

### ISSUE THREAD

**Issue by dzid26** [trinamic/TMCL-IDE-Nightly#13]
**CAN Secondary id** should be  83 on TMCM-1270, not 72.
![image](https://user-images.githubusercontent.com/841061/71709896-a77dc200-2dc7-11ea-918c-a721d18594af.png)
The status indicates "Wrong type" error

**Comment by dzid26** [comment]
SAP 77 - Short to ground protection.  
![image](https://user-images.githubusercontent.com/841061/71710502-92566280-2dca-11ea-866c-9f4403e14023.png)
It also produces error.

**Comment by dzid26** [comment]
Probably should be removed from https://github.com/trinamic/PyTrinamic/blob/master/PyTrinamic/modules/TMCM_1270.py as well.

**Comment by txf-** [comment]
This applies to TMCM-1276 too.

**Comment by trinamic-mj** [comment]
We will fix this and generate a new Nightly asp
