### ISSUE TITLE
Can you distribute the ide properly using github? 

### ISSUE THREAD

**Issue by txf-** [trinamic/TMCL-IDE-Nightly#15]
Why is this program being dumped on github in binary zipped blobs?

Why is github being used this way?

**Comment by dzid26** [comment]
Would make more sense if it was in Releases, if it is close-source.

But @trinamic would benefit open-sourcing it. Seems like there is a lot of small fixable issues in the software

**Comment by txf-** [comment]
It's fine if they want to do binary releases, but Github isn't the appropriate place for them to do it.
