### ISSUE TITLE
Supported CAN bus interfaces

### ISSUE THREAD

**Issue by rusoku** [trinamic/TMCL-IDE-Nightly#16]
Do you use standard and unmodified Qt serialbus plugins ? I would like to add TouCAN USB <-> CAN converter support. 
Seems like Qt plugin for RUSOKU TouCAN converter compiled based on Qt serialbus examples doesn't work.

**Comment by trinamic-mj** [comment]
We do not use the Qt plugins, this does not worh as aspected. We use tunktions the vendors' libraries; see QLibrary example.
