### ISSUE TITLE
Include file not found - TMCLParam.tmc

### ISSUE THREAD

**Issue by pettaa123** [trinamic/TMCL-IDE-Nightly#17]
ideLib: 1.2.0.0 - Qt 5.12.10
Version 0.0 64-Bit

On Ubuntu 20.04.2 LTS I get an error: Include file not found in line 1 using:
#include TMCLParam.tmc
I have one TMCLParam.tmc next to my program and one in \home\user\.config\TRINAMIC Motion Control GmbH & Co. KG\TMCL-IDE
Where does TMCL-IDE look for it? Further info: I'm using an older driver TMCM-310, is it because of that?

**Comment by trinamic-mj** [comment]
We are working on that issue. Problem is, file names are internally converted to uppercase letters. Renaming to TMCLPARAM.TMC could work?

**Comment by pettaa123** [comment]
I renamed the file next to executable and the one in \home\user.config\TRINAMIC Motion Control GmbH & Co. KG\TMCL-IDE but still include file not found error. Where does the linux version search for the file?

**Comment by trinamic-mj** [comment]
Upper and lower case is now taken into account.
