### ISSUE TITLE
Where does the monitoring motor supply voltage displayed on the left-top  corner of TMCL-IDE come from?

### ISSUE THREAD

**Issue by huskier** [trinamic/TMCL-IDE-Nightly#19]
Hi, we wonder where the monitoring motor supply voltage displayed on the left-top  corner of TMCL-IDE comes from? TMC4671's AGPI_A, AGPI_B, or ADC_VM?

We guess it is from ADC_VM. However, although we have the same ADC_VM input curcuit design following the TMC4671-eval board, we get different displayed value (47V~52V) from the evaluation board(23.4V). The motor supply is the same, 24V. 

![MonitoringMotorSupplyVoltage](https://user-images.githubusercontent.com/5828575/111267422-d992e100-8666-11eb-9d3a-dec3cf37884e.png)

**Comment by huskier** [comment]
@trinamic-mj  Hi, could you help us for the above issue?

**Comment by trinamic-mj** [comment]
Hi, This is not the right forum for this kind of help. Please use the Technical Support from trinamic.com.
someone told me it was iirc ADC_VM

**Comment by huskier** [comment]
Now, we have known where the displayed motor supply voltage in the TMCL-IDE  is from. It is from the L-Board's VM Measurement as the following diagram. Before, we always think it is from the TMC4671's ADC_VM.

Thanks for your help! @trinamic-mj 

![VMMeasurement_OK](https://user-images.githubusercontent.com/5828575/112708551-8eda5a00-8eed-11eb-8d9b-ff7dae4525cc.png)
