### ISSUE TITLE
Interpolation option for the MVP COORD command in TMCL Creator?

### ISSUE THREAD

**Issue by shadyrobots** [trinamic/TMCL-IDE-Nightly#2]
The manual describes the process of setting an interpolation bit within the motor parameter byte.
![image](https://user-images.githubusercontent.com/17055827/52019644-7496c400-24bc-11e9-8c09-94779ad68e0e.png)
We've made good use of this in direct mode, but there doesn't seem to be a way to input this into TMCL creator?

It looks like it can be done in direct mode by filling out the manual instruction input. The manual instruction input doesn't copy over to TMCL creator with the 0x43 in the motor parameter.
![image](https://user-images.githubusercontent.com/17055827/52019738-c8091200-24bc-11e9-801a-6ab6326d9189.png)

**Comment by trinamic-ok** [comment]
The Direct Mode dialogue does not support entering the motor numbers needed for MVP COORD, so the manual instruction input has to be used.
But the MVP COORD command with the needed motor number can also be directly entered in the TMCL Creator, so in the TMCL Creator for example enter something like:
MVP COORD, $43, 0

**Comment by trinamic-ok** [comment]
It looks as if this has not made its way into version 3.0.22. As a workaround, you can switch off parameter checking in the TMCL Creator (TMCL/Options, then uncheck "Check parameter ranges"). It will be solved in version 3.0.23.
