### ISSUE TITLE
High: ASCII mode and Reverse Shaft Direction cause loss of connection with driver

### ISSUE THREAD

**Issue by joao-pinhal-feup** [trinamic/TMCL-IDE-Nightly#20]
Hello, I am developing code for the Trinamic PD42-4-1140-TMCL motor driver and found that immediately after I change the Reverse Shaft Direction Global Parameter to 1, the USB connection to the driver is lost and I am forced to reset to factory settings to establish it again. 
In the same way, after I turn on the ASCII mode it does not work and after a while it also loses connection to the driver. I followed the packet structure in the firmware manual and it does not even respond with an error code through the serial connection. It isn't a serial connection problem because the binary mode works just fine.

Using TMCL-IDE 3.3.0.0.

Thank You,

João Pinhal

**Comment by trinamic-mj** [comment]
hello, the problem with the Shaft Direction is known and will be fixed in the next firmware version. The ASCII mode is only for older applications, please do not use it with TMCL-IDE, which works in binary mode only.
