### ISSUE TITLE
PI Tuning for TMC4671 - numberfield only accepts 0

### ISSUE THREAD

**Issue by Arktarus** [trinamic/TMCL-IDE-Nightly#28]
We would like to tune the PI parameters of the TMC4671-EVAL board with the TMCL-IDE 3.6.x software.

Unfortunately the Step Settings > Target numberfield only accepts 0. Using another laptop or other keyboard does not allow entering a number other than zero.

Starting with this setting results in an error (see attached).

![image_2022-07-14_21-59-28](https://user-images.githubusercontent.com/67394197/179175785-a31ad367-fb52-49c2-8d67-d9bd4739c6d0.png)

The Flux limit was set to 8000 mA.

This bug was confirmed on two Win10 64-bit machines on software version 3.6.0 and 3.6.2.

**Comment by trinamic-ed** [comment]
![grafik](https://user-images.githubusercontent.com/1303462/179753896-e6ea13b9-cfe2-462b-b240-e1b71a1d22ed.png)

Hi,

please check if you are using the newest firmware for the Landungsbrücke. (The newest firmware is available here: https://github.com/trinamic/TMC-EvalSystem/releases/tag/3.08.17 )

In the "Limit" window, the raw register content for "PID_TORQUE_FLUX_LIMITS" is shown. A value of 2000 in 0x5E is equal to the value of 2304 [mA] when reading the axis parameter 6: "get axis parameter" with the TMC6100-EVAL powerstage. The axis parameter 6 is used to limit the target current in the PI-Tuning tool.

The axis parameter 6 has been added in the last firmware / IDE version.

Regards,
      Enrico
