### ISSUE TITLE
 TMCL-IDE 3.6.x (Windows 10) is (still) almost unusable

### ISSUE THREAD

**Issue by clayhaight01** [trinamic/TMCL-IDE-Nightly#29]
The previous thread titled "TMCL-IDE 3.6.x (Windows 10) is almost unusable" was closed because apparently the issues were fixed in the new nightly build (3.6.4.0). The issues were not fixed, al the issues still persist. See image below:
![2022-08-08 12_31_42-Settings](https://user-images.githubusercontent.com/3269602/183468598-c83a90d1-b4c8-4526-a5f8-0a2620a2736c.png)

**Comment by trinamic-mj** [comment]
I just compile a new version.

**Comment by trinamic-mj** [comment]
I have simply replaced the zip

**Comment by clayhaight01** [comment]
Every new version gets slower and slower. This recent version takes around 1sec/line of TMC code to assemble.

**Comment by trinamic-mj** [comment]
![grafik](https://user-images.githubusercontent.com/9270204/183609313-4e6f8baf-927f-4d48-8237-5a81f1ac3969.png)
Have you made any changes here?

**Comment by huskier** [comment]
@trinamic-mj Hi, the latest version V3.6.4 is still unusable. It always says "No response", and the GUI just freeze there!

Our system is Win10_x64. Is it possible that the released version is x86, not x64 which cause the problem? Or, are there any language settings or local settings which cause the issue? 

BTW, is it possible to open source part of the TMCL-IDE? Keep your products related code in private. In this way, we could be possible to help a little bit.

![Still_Unuseable](https://user-images.githubusercontent.com/5828575/184048276-1e55ee07-f5dc-44c7-aff4-f00302ea17c9.png)

**Comment by trinamic-mj** [comment]
I do not know now how I can help further. Everything seems to work: 
![grafik](https://user-images.githubusercontent.com/9270204/184080682-0721cfc1-fb6d-47aa-9a76-a23c16051c64.png)

**Comment by huskier** [comment]
It's very weird.  We've really encountered the "No response" stuck.

Our OS info as following:
Windows 10 Enterprise LTSC
Version 1809, Internal version 17763.3046
x64

We've found the program is 32bit. Could you please compile a x64bit release version?
![image](https://user-images.githubusercontent.com/5828575/184085310-3e8e057d-0f13-4b6e-a14a-129064e2a024.png)

Or, maybe we try other Win10 OS.

**Comment by huskier** [comment]
Actually, V3.2.0 is OK. The behavior of V3.6.4 is different from V3.2.0, and it is very sluggish.

@trinamic-mj, do you really tuning something, or just open some windows?

**Comment by trinamic-mj** [comment]
Yes, I tuned some values with the Wizard

**Comment by huskier** [comment]
The Wizard part is probably no problem. We think the issue mostly comes from the tuning part. Maybe the GUI update frequency is the main problem. Sometimes, it is needed to wait several seconds to input a number(or parameter) ; sometimes, the mouse becomes a waiting circle, just "No Response".

There are smooth version there, say V3.2.0, and the previous other versions before V3.2.0. Maybe there are some important variables which have been changed during the upgrading development.

We mainly use the IDE to tune TMC4671 through RTMI interface.
