### ISSUE TITLE
When click the "Set defaults" button in Wizard's "Open Loop settings", there are no any changes for the registers' value in the "Open loop configuration" part.

### ISSUE THREAD

**Issue by huskier** [trinamic/TMCL-IDE-Nightly#30]
Normally, when we click the "Set defaults" button in Wizard's "Open Loop settings",   the registers' value in the "Open loop configuration" part should be changed accordingly for open loop motion.

However, for one of our axes, when we click the "Set defaults" button in Wizard's "Open Loop settings", there are no any changes for the registers' value in the "Open loop configuration" part. Other axes are work properly, there is no this problem.

We wonder what's the reason for this weird behavior? We confirm that the RTMI is correctly connected to the TMC4671, and the TMCL-IDE has found the TMC4671.

Is this a software-related problem? When we click the "Set defaults" button, are there any operations between the TMCL-IDE and the TMC4671+TMC6200?

![image](https://user-images.githubusercontent.com/5828575/184301191-4000bd84-0585-41d3-8b0a-701954afe6d2.png)

**Comment by trinamic-mj** [comment]
We will check that why with RTMI some defaults do not work.
