### ISSUE TITLE
Microstep Resolution not written to module when using "Module Settings"

### ISSUE THREAD

**Issue by Andy1978** [trinamic/TMCL-IDE-Nightly#35]
Both, the stable TMCL-IDE 3.6.0.0 and testing 3.6.8.1 both show the same problem:

![microstepping](https://github.com/trinamic/TMCL-IDE-Nightly/assets/240064/c37fd017-3a4e-4b7f-8a71-46da1696288d)

If you use "Module Settings" -> "Microstep" Tab and use the dropdown to change the microstep resolution I would expect to see some "SAP 140, 0, X" command on the logfile but the changed value isn't send to the module.

"Store Current Tab" sends STAP 140, 141, 142 as expected.

I think this obviously is a bug in the IDE, perhaps the programmer forgot the "onChange callback action" for the DropDown and the other checkboxes on that tab.

**Comment by Andy1978** [comment]
Same for StealthChop, SpreadCycle and CoolStep Tab. Only changes on the "Current" tab are written to the module, which makes the IDE quite useless for TMCM-1076.

**Comment by trinamic-mj** [comment]
We will take care of it as soon as possible.

**Comment by Andy1978** [comment]
Okay, this has been closed after 3 months (as soon as possible) as completed. Thank you for your quick response

But I can't find a new download where this is fixed.

**Comment by trinamic-mj** [comment]
Sorry for the delay, the Linux version should be available next week.

**Comment by trinamic-mj** [comment]
Add v3.11.0
