### ISSUE TITLE
No microstepping settings

### ISSUE THREAD

**Issue by szym1998** [trinamic/TMCL-IDE-Nightly#37]
I can not find any settings regarding microstepping for tmc2209 am I doing something wrong? 

![Screenshot 2023-08-01 113341](https://github.com/trinamic/TMCL-IDE-Nightly/assets/18391903/df244436-bd0e-4dde-b66d-e0c1f913a497)

**Comment by trinamic-mj** [comment]
I'll pass that along.

**Comment by trinamic-mj** [comment]
We don't have microstep settings for TMC2209-eval in there. But one can change the resolution through direct mode.
![grafik](https://github.com/trinamic/TMCL-IDE-Nightly/assets/9270204/e00df284-4b9d-422e-a607-2426c4189333)
