### ISSUE TITLE
Request for Open Sourcing TMCL-IDE QT Code

### ISSUE THREAD

**Issue by yasir-shahzad** [trinamic/TMCL-IDE-Nightly#38]
I wanted to kindly request the open sourcing of the QT code for TMCL-IDE. Making this code available would not only benefit the community but also foster collaboration and innovation. Your consideration of this request would be greatly appreciated.

**Comment by trinamic-ed** [comment]
Hello Yasir,

sorry, but in the moment we do not plan to make the TMCL-IDE open source.
