### ISSUE TITLE
Linux Support for TMC5161

### ISSUE THREAD

**Issue by euphi** [trinamic/TMCL-IDE-Nightly#4]
When there will be a Linux version available for an IDE that supports TMC5161?

Or is there a way to support 5161 with the current Linux version? I tried to set the chip to TMC5160 with "unknown" driver, but this does not work.

**Comment by trinamic-mj** [comment]
5160 should be work,  cause same registers. Chose "none" driver.
We get new development resource and a Linux version will coming soon.

**Comment by trinamic-mj** [comment]
I found a little time... A new Linux version is available!
The bin folder only contains lib's needed by Qt (and openssl). If something is missing install matched packages
