### ISSUE TITLE
Settings Export doesn't work

### ISSUE THREAD

**Issue by dzid26** [trinamic/TMCL-IDE-Nightly#8]
After selecting *.TMCL/*.ini file path to save, the Saving Settings windows loops forever and doesn't save selected file
![image](https://user-images.githubusercontent.com/841061/70382850-ee93a700-1930-11ea-9f1d-d53dbbb22255.png)

**Comment by trinamic-mj** [comment]
There was only one parameter to save. It was saved, but the progress bar values were set wrong.
